'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On
'Imports Elegant.Ui

<Assembly: Elegant.Ui.CommandSourceAttribute("Books.ApplicationCommands", "Books.Books.ApplicationCommands")>
Namespace Books

    ' This class is required for commands suppport.
    ' Do not modify this code inside the editor.

    Public Class ApplicationCommands

    End Class


End Namespace

